// Mock data for artists
export const mockArtists = [
  {
    id: 1,
    name: "Sarah Johnson",
    category: "Singer",
    bio: "Professional jazz and pop vocalist with 10+ years experience",
    priceRange: "$500-1000",
    location: "New York, NY",
    image: "https://images.unsplash.com/photo-1494790108755-2616b79b94ad?w=400",
    rating: 4.9,
    completedEvents: 150,
    languages: ["English", "Spanish"],
    verified: true,
  },
  {
    id: 2,
    name: "Michael Chen",
    category: "DJ",
    bio: "Electronic music specialist for weddings and corporate events",
    priceRange: "$300-800",
    location: "Los Angeles, CA",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    rating: 4.8,
    completedEvents: 200,
    languages: ["English", "Mandarin"],
    verified: true,
  },
  {
    id: 3,
    name: "Elena Rodriguez",
    category: "Dancer",
    bio: "Contemporary and Latin dance performer and choreographer",
    priceRange: "$400-900",
    location: "Miami, FL",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400",
    rating: 4.9,
    completedEvents: 120,
    languages: ["English", "Spanish", "Portuguese"],
    verified: true,
  },
  {
    id: 4,
    name: "Dr. James Wilson",
    category: "Speaker",
    bio: "Motivational speaker and business consultant",
    priceRange: "$1000-2500",
    location: "Chicago, IL",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
    rating: 4.7,
    completedEvents: 80,
    languages: ["English"],
    verified: true,
  },
  {
    id: 5,
    name: "Lisa Park",
    category: "Singer",
    bio: "Classical opera singer with international experience",
    priceRange: "$800-1500",
    location: "San Francisco, CA",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
    rating: 4.8,
    completedEvents: 90,
    languages: ["English", "Italian", "French"],
    verified: true,
  },
  {
    id: 6,
    name: "Carlos Martinez",
    category: "Dancer",
    bio: "Professional ballroom and salsa dance instructor",
    priceRange: "$350-700",
    location: "Austin, TX",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    rating: 4.6,
    completedEvents: 110,
    languages: ["English", "Spanish"],
    verified: false,
  },
];

export const categories = ["all", "Singer", "DJ", "Dancer", "Speaker"];

export const locations = [
  "all",
  "New York",
  "Los Angeles",
  "Miami",
  "Chicago",
  "San Francisco",
  "Austin",
];

export const priceRanges = [
  { value: "all", label: "All Prices" },
  { value: "budget", label: "Budget ($300-500)" },
  { value: "mid", label: "Mid-range ($500-1000)" },
  { value: "premium", label: "Premium ($1000+)" },
];
